
export namespace Prefixes {

    export const biocad:string = 'http://api.biocad.io/terms#'
}

export namespace Predicates {

    export const autogeneratedTitle:string = Prefixes.biocad + 'autogeneratedTitle'

}